version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

executors:
  buildpack_deps:
    working_directory: ~/repo
    docker:
      - image: circleci/buildpack-deps:curl

jobs:
  wake_bolt:
    executor: buildpack_deps
    steps:
      - run: |
          curl -X POST -i -m 30 https://sugarshin-bolt.herokuapp.com/heroku-keepalive || :

workflows:
  # this is for only testing
  wake_bolt_test:
    jobs:
      - wake_bolt:
          filters:
            branches:
              only: wake-bolt-test
  wake_bolt_daily:
    triggers:
      - schedule:
          cron: "5 22 * * *" # JST AM07:05
          filters:
            branches:
              only:
                - master
    jobs:
      - wake_bolt
