version: 2.1

orbs:
  node: circleci/node@4.1.0

executors:
  base:
    docker:
      - image: cimg/base:current-22.04
  nodejs:
    docker:
      - image: cimg/node:12.22.12

jobs:
  wake_bolt:
    executor: base
    steps:
      - run: |
          curl -X POST -i -m 30 https://sugarshin-bolt.onrender.com/keepalive || :
  lint_and_tsc:
    executor: nodejs
    steps:
      - checkout
      - node/install-packages:
          include-branch-in-cache-key: false
      - run: npm run lint:ci
      - run:
          command: npm run build -- --noEmit
          environment:
            NODE_ENV: production

workflows:
  test_build_deploy:
    jobs:
      - lint_and_tsc

  # this is for only testing
  wake_bolt_test:
    jobs:
      - wake_bolt:
          filters:
            branches:
              only: wake-bolt-test
  wake_bolt_daily:
    triggers:
      - schedule:
          cron: "5 22 * * *" # JST AM07:05
          filters:
            branches:
              only:
                - master
    jobs:
      - wake_bolt
